### ISSUE TITLE
Cannot import name 'pinvh'

### ISSUE THREAD

**Issue by cpwang007** [scikit-learn-contrib/metric-learn#213] opened 2019-06-11 16:51 UTC
#### Description
Cannot import metric_learn

#### Steps/Code to Reproduce

Example:
```python
from metric_learn import MLKR
```

#### Versions
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import sklearn; print("Scikit-Learn", sklearn.__version__)
import metric_learn; print("Metric-Learn", metric_learn.__version__)

Linux-4.9.152-0.1.ac.221.79.329.metal1.x86_64-x86_64-with-redhat-5.3-Tikanga
Python 3.6.8 |Anaconda custom (64-bit)| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]
NumPy 1.16.4
SciPy 1.2.1
Scikit-Learn 0.21.2

**Comment by wdevazelhes** [comment] 2019-06-12 07:13
Hi @cpwang007, thanks for reporting this error. Could you provide the full error trace (for instance does it contain `ImportError: cannot import name 'pinvh'`)? This might be a duplicate of #209

**Comment by cpwang007** [comment] 2019-06-12 20:24
yes, it is a duplicate of that.

**Comment by bellet** [comment] 2019-09-03 08:00
This is solved with the new release

**Closed by bellet** 2019-09-03 08:00 UTC
